# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{devise_omniauth_engine}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John McAliley"]
  s.date = %q{2011-05-11}
  s.description = %q{devise/omniauth shortcut}
  s.email = %q{john.mcaliley@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/controllers/users/omniauth_callbacks_controller.rb",
    "app/controllers/users_controller.rb",
    "app/models/authentication.rb",
    "app/models/omniauth_user.rb",
    "app/views/devise/shared/_links.erb",
    "app/views/users/index.html.erb",
    "config/yettings/devise_omniauth_engine.yml",
    "devise_omniauth_engine.gemspec",
    "lib/devise_omniauth_engine.rb",
    "lib/devise_omniauth_engine/engine.rb",
    "lib/generators/devise_omniauth_engine/install/USAGE",
    "lib/generators/devise_omniauth_engine/install/install_generator.rb",
    "lib/generators/devise_omniauth_engine/install/templates/db/migrate/create_authentications_table.rb"
  ]
  s.homepage = %q{http://github.com/johnmcaliley/devise_omniauth_engine}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Shortcut for devise and omniauth}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, [">= 0"])
      s.add_runtime_dependency(%q<omniauth>, [">= 0"])
      s.add_runtime_dependency(%q<yettings>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<devise>, [">= 0"])
      s.add_dependency(%q<omniauth>, [">= 0"])
      s.add_dependency(%q<yettings>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.1"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<devise>, [">= 0"])
    s.add_dependency(%q<omniauth>, [">= 0"])
    s.add_dependency(%q<yettings>, [">= 0"])
  end
end

