defaults: &defaults
  #TEST TWITTER KEY
  twitter_key: 7aS9miLM9O1wcqV7SPw
  twitter_secret: PjLYk6acABRcbM7xsc7dCUIhfGrRGIb0s89t7ZwcE
  #TEST FB app
  facebook_key: 814feae9e446c24796b3210ad7f3567f
  facebook_secret: a95127a3842bc45a82199e3eceb9b837
  
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
  twitter_key: YOUR TWITTER APP KEY HERE
  twitter_secret: YOUR TWITTER APP SECRET HERE
  facebook_key: YOUR FACEBOOK APP KEY HERE
  facebook_secret: YOUR FACEBOOK APP SECRET HERE
  